### ISSUE TITLE
Develop some heuristics to correct the dependency tree

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-QuestionParsing-Grammatical#107]
There are some mistakes done by the dependency tree that could be corrected before using our algorithms. This issue has 2 goals:
  - [x] Build the architecture to quickly and easily add heuristics that correct the dependency tree before we analyze it
  - [x] Develop a first heuristic to add a named entity tag. [See here](https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/pull/106) the MWE bug

**Comment by yhamoudi** [comment]
Some sentences mis-parsed (to get some ideas of heuristics):
* What country is the biggest producer of tungsten?
* Who are the The Rolling Stones members?
* Is 42 an integer?
* Whose gender is genderqueer?
* How to get to the ENS Lyon?
* Are there pets on the farm?
* Are there geocaches in this forest?
* What albums did Pearl Jam record? (record est probablement mal taggé)
* Which movies does Quentin Tarantino star in? (idem)
* Which movies did Quentin Tarantino direct, but not star in?
* Are there beers in Germany?
* Show me Star Wars movies
* What country is the biggest producer of tungsten?
* How long did the Charles Manson murder trial last?
* What kind of animal is Babar?
* Which movies does Quentin Tarantino star in?
* What U.S. state is Fort Knox in?
* What city is Purdue University in?
* When was Benjamin Disraeli prime minister?
* list of president of usa
* Show me Star Wars movies

**Comment by Ezibenroc** [comment]
> Build the architecture to quickly and easily add heuristics that correct the dependency tree before we analyze it

What do you think of? How would be the best (feasible) way to add heuristics according to you?

**Comment by yhamoudi** [comment]
perhaps a new file in which we only add this kind of heuristics. When i say `Build the architecture` it's just to avoid adding the heuristics in `preprocessing.py` for instance, not to build something complicated

**Comment by Ezibenroc** [comment]
A file `prepreprocessing.py` maybe? :)

**Comment by yhamoudi** [comment]
and then `postprepreprocessing.py` ?

**Comment by yhamoudi** [comment]
Fix https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/pull/108
