### ISSUE TITLE
Cop dependency

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-QuestionParsing-Grammatical#109]
Several questions contain `cop` dependency (and thus raise a `GrammaticalError` exception):

* "What is the UN headquarter?"
* "What is the United States national day?"

**Comment by yhamoudi** [comment]
Others were still referenced in `Hierarchy_review.md`. Is it ok if i add them to this file and close this issue (there is no solution, it's a problem of parsing).

**Comment by Ezibenroc** [comment]
Ok.
