### ISSUE TITLE
Datamodel Python - Change a predicate

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-QuestionParsing-Grammatical#115]
I try to change the predicate of a `Triple` node `n` by doing: `n.predicate = ...`. However i obtain the error `AttributeError: 'Triple' object has no attribute 'predicate'`

You can reproduce the error using the file `demo8.py` (in `demo` folder) and the question `Who am i`

**Comment by yhamoudi** [comment]
It's really strange. I can access `n.predicate` (`print(n.predicate)` works) but not change it

**Comment by yhamoudi** [comment]
So how can i do? I need to rebuild all the normal form?

**Comment by ProgVal** [comment]
Yes.

Mutable tree generally are not a good idea, unless you want to spend a lot of time debugging weird bugs.

**Comment by yhamoudi** [comment]
ok. 

Let's imagine i have a node `n` whose type belongs to `(List,Intersection,Union,And,Or,Last,First,Exists)`. I would like to build a normal form identical to `n` except that `n.list` contains one new element `a`.

I could split this task:
```python
if isinstance(n,List):
  return List(n.list+[a])
elif isinstance(n,Intersection):
  return Intersection(n.list+[a])
...
```
Is there a way to do this quicker?

**Comment by yhamoudi** [comment]
Finally, i've done:
```python
if isinstance(n,(List,Intersection,Union,And,Or,Last,First,Exists)):
    return type(n)(n.list+[a])
```
