### ISSUE TITLE
“What follows "Searchers Search"?”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#135]
It should be `(?, follows, Searchers Search)`, not `(Searchers Search, [big list], ?)`

http://askplatyp.us/?lang=en&q=What+follows+%22Searchers+Search%22%3F

**Comment by ProgVal** [comment]
Or eventually, `(Searchers Search, followed by, ?)` (both work on Wikidata)

**Comment by yhamoudi** [comment]
Fixed https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/commit/9153da5e3ef7f8ef9d489b295594852c683f06e3 (you should deploy the latest version, the triple `(?, follows, Searchers Search)` was not produce since a long time)
