### ISSUE TITLE
"Where is the ENS Lyon?" is not parsed anymore

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#142]
See: http://askplatyp.us/?lang=en&q=Where+is+the+ENS+Lyon%3F

**Comment by yhamoudi** [comment]
It works with the latest version (see https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/116 and bottom of https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/138)

**Comment by Tpt** [comment]
Thank you. I should have look for this issue in the closed bug.

@ProgVal We should maybe deploy a version of the NLP-grammatical where this issue is fixed.

**Comment by ProgVal** [comment]
> @ProgVal We should maybe deploy a version of the NLP-grammatical where this issue is fixed.

What do you mean?

**Comment by Tpt** [comment]
> What do you mean?

I believe that my sentence is clear: I'm just saying that we should deploy a new version of this module (and create one if it does not exists yet) that does not have this bug anymore.
