### ISSUE TITLE
Use the CoreNLP HTTP API

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#148]
CoreNLP has now an HTTP API. it would be nice to use it in order to have a more modular architecture and avoid the dependence on a CoreNLP Python wrapper.

API doc: https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

**Comment by Ezibenroc** [comment]
Good point, I will have a look in the next few days.

**Comment by Ezibenroc** [comment]
I just started to have a look, sorry for the delay.
This will be a more tedious work than I thought, since there has been changes in the library output format, and new grammatical dependencies are used (which obviously break our code...).

**Comment by Ezibenroc** [comment]
An example of the changes that occurred with the new version of CoreNLP.

This parse tree is obtained with the CoreNLP from 29/01/2015 (the one currently used in production) :
![and_old](https://cloud.githubusercontent.com/assets/8900834/13875657/7b2f467c-ecff-11e5-9dea-6c5dc911ebec.png)

This parse tree is obtained with the CoreNLP from 09/12/2015 (the one we would like to use) :
![and](https://cloud.githubusercontent.com/assets/8900834/13875656/7b2a33f8-ecff-11e5-855e-f88dcb5e2475.png)

These particular changes should not be a big issue.
