### ISSUE TITLE
There is no bootstrap_corenlp.sh in Scripts

### ISSUE THREAD

**Issue by always19** [ProjetPP/PPP-QuestionParsing-Grammatical#153]
I read https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/tree/master/demo
There was no `bootstrap_corenlp.sh` file.
Do you have plans to update README.md?

What I did is
```sh
pip install corenlp-python
cd ../.. # at parent of this repository
git clone https://github.com/ProjetPP/Scripts.git
cd Scripts
wget http://nlp.stanford.edu/software/stanford-corenlp-full-2014-08-27.zip
```

By the way, as demos access to port 9000,
not
`CORENLP="stanford-corenlp-full-2015-01-30" CORENLP_OPTIONS="-parse.flags \" -makeCopulaHead\"" python3 -m corenlp`
but
`CORENLP="stanford-corenlp-full-*" CORENLP_OPTIONS="-parse.flags \" -makeCopulaHead\"" python3 -m corenlp -p 9000`
seems to work.

**Comment by ProgVal** [comment]
Hi,

`bootstrap_corenlp.sh` is in this repo: https://github.com/ProjetPP/Deployment

I'll fix the README.

**Comment by always19** [comment]
Thanks!
