### ISSUE TITLE
Multiple possible words in each node

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-QuestionParsing-Grammatical#48]
During nounification/lemmatization/question word analysis: do not pick only one word/expression to replace the value of the node but put many possible values.

Ex: kills -> kill, killer, ...

**Comment by yhamoudi** [comment]
Let's talk about ConceptNet : https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/blob/conceptnet/demo/conceptnet.py

First remarks:
  - actually, if i'm not mistaken, the algorithm takes a word w as input, brings back all the related edges and looks at the 2 endpoint of each edge to determine where is the input word w and where is the related information. However, conceptnet performs lemmatization (https://groups.google.com/forum/#!topic/conceptnet-users/mbt6uprdJ4I) so the input word w can be modified by conceptnet = we obtain edges which endpoints don't contain the input word w. It's a problem because we do not choose the right endpoint if the word has been lematized
  - how does the parameter `'limit':` works (and how to get the same result than in the online demo)? For instance, it seems that `elector` is `RelatedTo` `elect` (http://conceptnet5.media.mit.edu/web/c/en/elect). I try to obtain it: i remove `if w['score']/r['maxScore']>=0.5]` and i increase `limit` but `elector` is never output

**Comment by Ezibenroc** [comment]
> * actually, if i'm not mistaken, the algorithm (...)

-> Good point. So we would need to cut the search in two parts: one where the searched word is on the left hand side, and one where it is on the right and side, depending on the relation.
But our code does not make lemmatization: [bagel](http://conceptnet5.media.mit.edu/data/5.2/search?text=bagel) returns 317 results whereas [bagels](http://conceptnet5.media.mit.edu/data/5.2/search?text=bagels) returns 0 result. I don't know how they do this lemmatization.

When installing conceptnet on my computer, I saw a dependency with NLTK. Maybe they use its lemmatizer (which returns very good results).

> * how does the parameter 'limit': works (...)

`limit` is just the max number of returned results. It is very strange that we do not obtain this relation...

**Comment by yhamoudi** [comment]
the normalization has been added into the file (using the normalizing tool of conceptnet)

**Comment by yhamoudi** [comment]
Some progress:
  - most of the available info about the API are here: https://github.com/commonsense/conceptnet5/wiki/API
  - about vocabulary: in conceptnet each information is represented by an __URI__. For instance, the concept `elect` is represented by the URI `/c/en/elect`. The relation `related to` by the URI `/r/RelatedTo`. When you enter a word into their website (`elected` for instance) it is mapped to an existing concept (`elect`) by normalization (mostly lemmatization + stemming). The distinction between words (string) and URI is important because some tools provided by conceptnet takes a word as input, ant others take URI
  - we can see that there are 3 ways of querying: Lookup, Search and Association. 
    - _Lookup_: it seems to be what is displayed on their website: http://conceptnet5.media.mit.edu/web/c/en/elect. It gives you all the edges with an endpoint that is __exactly__ the URI obtained from your input word. It's what we are looking for! However, I don't success to use it (for instance, replacing `api='http://conceptnet5.media.mit.edu/data/5.2/search'` by `api='http://conceptnet5.media.mit.edu/data/5.2'` in our code doesn't work). Moreover, according to the documentation there are only 3 additionnal arguments available to get info with this method (limit, offset, filter)
    - _Search_: (it's what we use currently in our code) a lot of additionnal arguments available. Some of them need URI and other strings (words). The most important thing: it seems that both words and URI given as input are considered as __prefix__. For instance, if i perform a query using the argument `text` : i give a word as input (`elect` for instance) and then conceptnet returns all the edges with an endpoint (or a relation) __starting__ by `elect`. This is why the edge `elect -RelatedTo -> elector` is difficult to obtain : conceptnet considers that `power -RelatedTo-> electricity` is more relevant for instance.
    - Association: seems not interessant for the moment

So we have to find a way to extract all the edges that contain an endpoint that is exactly the input concept (and not all the edges for which the input concept is a prefix of one of the 2 endpoints). It would be good to perform queries using the optionnal arguments provided by  _Search_ (especially being able to select all the edges that contain a specified relation such as `RelatedTo`), and it's not sure we can do this with _Lookup_.

**Comment by yhamoudi** [comment]
implemented in this branch: https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/tree/multiple_nodes 

It remains to review the code / fix the unittests. Perhaps we could improve nounification before (https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/77)

**Comment by yhamoudi** [comment]
Finished in branch `multiple_nodes` \o/
