### ISSUE TITLE
"In which band does Bono sing?"

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-QuestionParsing-Grammatical#61]
The question "In which band does Bono sing?" raises the exception 

```
ppp_questionparsing_grammatical.data.exceptions.QuestionWordError: (<ppp_questionparsing_grammatical.preprocessing.DependenciesTree object at 0x7f982f57a790>, 'sentence without any word')
```

The dependency tree is the following:
![test](https://cloud.githubusercontent.com/assets/8900834/5381534/87f8916c-80a2-11e4-802b-24d6b6c025f6.jpg)

Does not seem too ugly.

**Comment by ProgVal** [comment]
Does not seem to work anymore (parsed as `(band,song,?)∩(Bono,song,?)`).
Should I reopen the issue?

**Comment by yhamoudi** [comment]
I don't think this issue was about the relevance of the result. It was about an exception uncaught.
