### ISSUE TITLE
Display trees in 2D

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-QuestionParsing-Grammatical#62]
Same goal as here: https://github.com/ProjetPP/PPP-WebUI/issues/13 It's became too difficult to understand the normal form we produce in demo6.py for instance

Algorithm: very similar to `normalize` (into `normalization.py`). Instead of returning the normal form, you build recursively the tree in dot format

**Comment by Ezibenroc** [comment]
Moved here: https://github.com/ProjetPP/PPP-datamodel-Python/issues/33
