### ISSUE TITLE
“Whose gender is genderqueer?”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#63]
I think it should be `(?, gender, genderqueer)`, not `gender∩(genderqueer,owner,?)`

Also, it doesn't parse “Who is genderqueer?” correctly (`(genderqueer,identity,?)` instead of  `(?, gender, genderqueer)`), but I don't think you can do much for that case.

**Comment by yhamoudi** [comment]
Not solved but registred
