### ISSUE TITLE
“Sum from 1 to n of f(x)”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#69]
`(1,Sum,?)∩(((?,x,f),n,?),Sum,?)` instead of ??? (is it even possible with the current datamodel?)

http://askplatyp.us/?lang=en&q=Sum+from+1+to+n+of+f%28x%29

**Comment by Ezibenroc** [comment]
Handled by [NaturalMath module](https://github.com/ProjetPP/PPP-NaturalMath).
