### ISSUE TITLE
"How many bla does bli have?"

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-QuestionParsing-Grammatical#75]
[How many children does Barack Obama have?](http://askplatyp.us/?lang=en&q=How+many+children+does+Barack+Obama+have%3F)

Here is the dependency tree:
![tmp](https://cloud.githubusercontent.com/assets/8900834/5742170/7a088790-9c10-11e4-8424-e08c65bd81f5.png)

I think we should not do an intersection each time a node have several child.

**Comment by yhamoudi** [comment]
Not solved but registered
