### ISSUE TITLE
"When is the birth of X?"

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#85]
Example: http://askplatyp.us/?lang=en&q=When+is+the+birth+of+Barack+Obama%3F

**Comment by yhamoudi** [comment]
Possibility : collapse `((A, B, ?), C, ?)` to `(A, B+C, ?)` if  there exists b in B and c in C such that `b c` is an existing predicate (appears into our wikidata properties/aliases database for instance).

**Comment by Ezibenroc** [comment]
> Possibility : collapse ((A, B, ?), C, ?) to (A, B+C, ?) if there exists b in B and c in C such that b c is an existing predicate (appears into our wikidata properties/aliases database for instance).

+1, but only if all b in B or all c in C do not exist in our database.

**Comment by yhamoudi** [comment]
See https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/64

**Comment by yhamoudi** [comment]
See https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/123
