### ISSUE TITLE
Support "show me" questions

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#89]
Example: "show me Star Wars movies".

I believe that the "show me" should be completely ignored.

**Comment by yhamoudi** [comment]
I add:
  - __Show me__ Star Wars movies
  - __List__ movies directed by Spielberg
  - __List__ books by Roald Dahl
  - __List__ albums of Pink Floyd
  - __List__ films with Jack Nicholson
  - __Give me__ the capital of France
  - (write down your ideas, especially all the words that can start this kind of questions)

The parsing of "show me Star Wars movies" is probably false. The query "List movies directed by Spielberg" is difficult to analyze (i have observed the same problem with a lot of different questions, i list them before we try to solve it, but it's not link to this issue).

**Comment by Ezibenroc** [comment]
There is a lot of variants for a given verb: "show", "show us", "show him", "show them".

**Comment by yhamoudi** [comment]
give them all (~~"show him", "show them".~~)

**Comment by Ezibenroc** [comment]
We should support "show him/her" and "show them", there is true life use cases, for instance if you present our amazing app to someone (or at our next public demonstration).

**Comment by yhamoudi** [comment]
ok...
