### ISSUE TITLE
"Of which country is Paris the capital?"

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-QuestionParsing-Grammatical#92]
[Of which country is Paris the capital?](http://askplatyp.us/?lang=en&q=Of+which+country+is+Paris+the+capital%3F)

Obtained: `(country,identity,?)∩(?,identity,Paris)∩(capital,identity,?)`
Expected: `(?, capital, Paris)`

![tmp](https://cloud.githubusercontent.com/assets/8900834/5988266/645a9ce8-a959-11e4-92da-dd46c1c11c72.png)

**Comment by Ezibenroc** [comment]
Remark: for Wolfram, [the American Paris is more relevant than the French Paris](http://www.wolframalpha.com/input/?i=From+which+country+is+Paris+the+capital%3F).

**Comment by ProgVal** [comment]
Isn't “Of which country is Paris the capital?” a more valid question?

**Comment by Ezibenroc** [comment]
> Isn't “Of which country is Paris the capital?” a more valid question?

Yes it is, since "Paris is the capital from France" is incorrect whereas "Paris is the capital of France" is not.

**Comment by s-i-newton** [comment]
http://www.wolframalpha.com/input/?i=Of+which+country+is+Paris+the+capital%3F
Better.

Le 31/01/2015 14:52, Valentin Lorentz a écrit :
>
> Isn't “Of which country is Paris the capital?” a more valid question?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/92#issuecomment-72318495>.
>

-- 

Marc Chevalier

ENS de Lyon
Site Monod
M1 Informatique Fondamentale

**Comment by yhamoudi** [comment]
the parsing is not good. The subject is not `the capital` (if it was well parsed i think we'll have the good normal form)
