### ISSUE TITLE
“What is the English for "Je suis élève à l’ENS de Lyon”?”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#93]
http://askplatyp.us/?lang=en&q=What+is+the+English+for+%22Je+suis+%C3%A9l%C3%A8ve+%C3%A0+l%E2%80%99ENS+de+Lyon%E2%80%9D%3F

**Comment by yhamoudi** [comment]
Very nice, the apostrophe `l'ENS` breaks the quotation handler algorithm :)

**Comment by Ezibenroc** [comment]
It is expected. Works well if we put the correct apostrophe: http://askplatyp.us/?lang=en&q=What+is+the+English+for+%22Je+suis+%C3%A9l%C3%A8ve+%C3%A0+l%27ENS+de+Lyon%E2%80%9D%3F

**Comment by Ezibenroc** [comment]
The question is: do we consider `’` as a quotation mark or an apostrophe (in a previous issue, we considered it as a quotation mark).

**Comment by ProgVal** [comment]
`'` is not not the “correct” apostrophe in French; `’` is. https://fr.wikipedia.org/wiki/Apostrophe_%28typographie%29#Aspect

**Comment by yhamoudi** [comment]
When `’` is between 2 letters we can consider that it's not an apostrophe. Same thing if `"` is used into the question.

There is also the case : `The Wilsons' dog and the Wilsons' car` (two `'` but both have letters on their left)

**Comment by Ezibenroc** [comment]
In this issue, you asked for support of a lot of quotation marks: https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/53

I think we should not support the following: `‘ ’ ' '`.

**Comment by Ezibenroc** [comment]
After further reading of the [Wikipedia page](http://en.wikipedia.org/wiki/Quotation_mark), it seems that the quotation mark symbol depends on the language and on the nestedness (primary and secondary quotation marks...).

I think these are typographic details, and that we do not have to handle them. We could detail explicitely on the website what are the allowed quotation marks.
