### ISSUE TITLE
"Who is the fourth president of the United States?"

### ISSUE THREAD

**Issue by Ezibenroc** [ProjetPP/PPP-QuestionParsing-Grammatical#95]
[Who is the fourth president of the United States?](http://askplatyp.us/?lang=en&q=Who+is+the+fourth+president+of+the+United+States%3F)
produces `first(sort((United States,president,?),"default"))`

The returned value is the same as:

[Who is the first president of the United States?](http://askplatyp.us/?lang=en&q=Who+is+the+first+president+of+the+United+States%3F)
produces `first(sort((United States,president,?),"default"))`

I don't know what is the expected returned value. I think we cannot describe it with the actual datamodel, since there is no operator for other ordinals than `First` and `Last`, and there is no operator for list difference.

**Comment by yhamoudi** [comment]
open a bug on the documentation repository

**Comment by yhamoudi** [comment]
Still considered here: https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/56
