### ISSUE TITLE
"What is forcing?"

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#98]
See: http://askplatyp.us/?lang=en&q=what+is+forcing%3F

It should return (forcing, definition, ?)

**Comment by Ezibenroc** [comment]
The CoreNLP parse "forcing" as a verb (in be+ing tense).

![tmp](https://cloud.githubusercontent.com/assets/8900834/6004180/3175cfe2-ab01-11e4-932a-b865d8e41a2c.png)

**Comment by yhamoudi** [comment]
Problem from the Stanford Parser, the question has been registred for future training
